{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "SampleHelm.serviceAccountName" . }}
  labels:
{{ include "SampleHelm.labels" . | indent 4 }}
{{- end -}}
